### ISSUE TITLE
YAML with emoji fails

### ISSUE THREAD

**Issue by syropian** [connec/yaml-js#28]
Throws `this.character.charCodeAt is not a function(…)`

I'm not sure emoji is even ever valid in YAML, but in case it is, the loader chokes with it. If it isn't, feel free to close this 😅

**Comment by connec** [comment]
Interesting!  If you post the YAML document that's failing I'll look into it when I can 😄

**Comment by syropian** [comment]
Sure! You can grab it here http://d.pr/f/1kVn3

**Comment by klokane** [comment]
Hi, we have same problem with unicode char U+1F60E (Smiling face with sunglases). It comes from external source, but it cripple our processing tool.

I investigate for reason.

It is because https://github.com/connec/yaml-js/blob/master/src/lib/reader.coffee#L19

There is check for NON_PRINTABLE character set. But there is explicit range for allowed chars.
If I comment calling `@check_printable()` it is parsed correctly.

So I propose instead of checking for "allowed set" of unicode chars, check just for a few dangerous char, like `\u2028` or `\u2029`

Is it acceptable solution for you @connec? I'm able to delivery PR in this case

Cheers

**Comment by pksunkara** [comment]
@connec Can we get a comment on this?

**Comment by connec** [comment]
Sorry for the delay investigating this. I tweaked the `NON_PRINTABLE` regular expression to allow code points above `0xFFFF`. For reference I tweaked a regex created by [regenerate](https://github.com/mathiasbynens/regenerate).

**Comment by pksunkara** [comment]
@connec Can we get a npm release please?

**Comment by connec** [comment]
@pksunkara published 0.1.5!
