### ISSUE TITLE
require.extensions is not supported by webpack. Use a loader instead.

### ISSUE THREAD

**Issue by naivefun** [connec/yaml-js#42]
Using from create-react-app and swagger-editor
version 0.2.3

```
Compiled with warnings.

./node_modules/yaml-js/lib/yaml.js
256:40-47 Critical dependency: require function is used in a way in which dependencies cannot be statically extracted

./node_modules/yaml-js/lib/yaml.js
require.extensions is not supported by webpack. Use a loader instead.

./node_modules/yaml-js/lib/yaml.js
require.extensions is not supported by webpack. Use a loader instead.

./node_modules/yaml-js/lib/yaml.js
require.extensions is not supported by webpack. Use a loader instead.

Search for the keywords to learn more about each warning.
To ignore, add // eslint-disable-next-line to the line before.
```

**Comment by cilf** [comment]
I've got the same. @naivefun Have you found a way to deal with these warnings?

**Comment by ajitkayastha** [comment]
I am facing the same issue. Have any one of you found any solution to this?

**Comment by connec** [comment]
Thanks for the issue, but I'm going to close it since this repository is going to be archived. yaml-js has been unmaintained for some time, so it would be best to use something else.

---

In case this issue is still relevant to you, I believe this should have been fixed by https://github.com/connec/yaml-js/commit/20c58d85e1d778a11e021a40f661717c6498ef3d, so perhaps you need a newer version.
